active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.14184019857516134
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.9052554982032197
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 91
    test_after_at_least_seconds_step: 6
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0003123226689503262
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 37
    batch_size_test: 256
    cv_valid_ratio: 0.16052390441851971
    enough_count:
      image: 2297
      video: 701
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 454
    steps_per_epoch: 9
    train_info_sample: 308
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: true
    freeze_portion: 0.30000000000000004
    lr: 0.005567479294438172
    min_lr: 2.98980639445342e-06
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: Adam
    warm_up_epoch: 4
    warmup_multiplier: 2.5
    wd: 3.233455672217531e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
